### PR TITLE
Add deploy to GHCR action

### PR DESCRIPTION
**Pull request by maggie0002**
Adds a deploy to GHCR action to build and deploy the Docker images

### CODE REVIEW

**Comment by maggie0002** [comment]
Nudge

**Comment by andrewn** [comment]
@maggie0002 Thanks for the nudge, just merged!

This looks like a good approach, let's hope it all builds ok!

**Comment by andrewn** [comment]
`docker/metadata-action@v4` warns:

> Warning: ghcr is not a valid semver. More info: https://semver.org/
> [32](https://github.com/andrewn/librespot-docker/actions/runs/4120714049/jobs/7115717413#step:7:37) Warning: No Docker image version has been generated. Check tags input.

So I'm switching to trigger on `vx` tags which works

**Comment by andrewn** [comment]
@maggie0002 [Now there's this error](https://github.com/andrewn/librespot-docker/actions/runs/4120765831/jobs/7115822614#step:8:160):

```
Error: buildx failed with: ERROR: failed to solve: failed to parse stage name "balenalib/%%BALENA_ARCH%%-alpine:3.14-run": invalid reference format: repository name must be lowercase
```

It kind of makes sense, I need to figure out how to set `%%BALENA_ARCH%%` somehow. I'll do some searching, but any ideas?

**Comment by andrewn** [comment]
Ok, I ended up using `matrix` strategy to map `BALENA_ARCH` for each platform.

Then there was a problem with `cargo build` which is also fixed.

🎉  [Packages are available](https://github.com/andrewn/librespot-docker/pkgs/container/librespot-docker)!

I'm travelling so won't be able to test on a real pi until the end of February.

**Comment by maggie0002** [comment]
Amazing thanks! Some great fixes in here I wouldn't have thought of. 

Does this unpack all of the different architectures to build? 

```
${{ matrix.platforms }}
```

I was expecting there would be a arch tab like there is here: https://github.com/balena-labs-research/starter-interface/pkgs/container/bsi

And when running on a NUC I get the error:

```
WARNING: The requested image's platform (linux/arm/v6) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```

I wonder if it is only running for `linux/arm/v6` which is the first platform listed. 

I also wonder whether we need to use the balenaLib images at all. We could try with just `alpine:3.14` and then wouldn't need to pass in the different architectures. Of course your solution would be better to avoid changing things we don't need to, but if the standard Alpine containers work, it would be a way to simply the build. 

No rush though, enjoy your holiday :)

**Comment by andrewn** [comment]
I think I see the problem, the `matrix` strategy re-runs the job with each set of architectures so I guess the job that finishes last is the one that gets the tag in GHCR.

I'll try with just `alpine:3.14` and see if that builds ok and then we can remove the matrix. Otherwise, I'm not really sure how to workaround it.

**Comment by andrewn** [comment]
@maggie0002 What an ordeal. 

I've tried with the non-balena alpine images and couldn't get them to build. I was getting this kind of error

```
#15 313.2   no REF_DELTA found, cannot inject object; class=Indexer (15)
```
[Run #18](https://github.com/andrewn/librespot-docker/actions/runs/4134218828/jobs/7145086911#step:9:566)

I've tried to revert to the matrix strategy build [which worked before (#7)](https://github.com/andrewn/librespot-docker/actions/runs/4121497080/workflow) and now pretty consistently getting [rust errors related to running out of memory (e.g. #27)](https://github.com/andrewn/librespot-docker/actions/runs/4192949256).

I'm not sure what to try next?

**Comment by maggie0002** [comment]
What's this fix do?

```
      # Workaround cargo error failing build
      # https://github.com/marketplace/actions/docker-on-tmpfs
      # Error: https://github.com/andrewn/librespot-docker/actions/runs/4121241814/jobs/7116738264#step:8:567
      - name: Run Docker on tmpfs
        uses: JonasAlfredsson/docker-on-tmpfs@v1
        with:
          tmpfs_size: 5
          swap_size: 4
          swap_location: "/mnt/swapfile"
```

tmpfs may be written to RAM, which means if it is being stored in that directory then that directory is content is written to RAM, which may mean running out of memory?

**Comment by maggie0002** [comment]
May also want to try disabling the cache:  

`importing cache manifest from gha:2682110710969971717`

```
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

Could be an overlap of caches between the different builds.

**Comment by andrewn** [comment]
> What's this fix do?
> 
> ```
>       # Workaround cargo error failing build
>       # https://github.com/marketplace/actions/docker-on-tmpfs
>       # Error: https://github.com/andrewn/librespot-docker/actions/runs/4121241814/jobs/7116738264#step:8:567
>       - name: Run Docker on tmpfs
>         uses: JonasAlfredsson/docker-on-tmpfs@v1
> ```

This action works around an armv7 build issue that I was getting before.

> This action was created to solve a https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/30 that occurs when building the latest pip cryptography package inside a QEMU emulated linux/arm/v7 environment (e.g. Rasberry Pi) on a linux/amd64 computer.

It moves the whole docker build onto tmpfs so yeah, disk space is limited. But without it the build also fails.

**Comment by maggie0002** [comment]
Wow, these quick fixes are never quick huh. Really appreciate the help with this. 

Have you tried it again today? Worth doing a re-run just to check whether it was actually network issues like some of the errors suggest, perhaps the GitHub workflows were just having a bit of a moment.

**Comment by andrewn** [comment]
I've been running a slightly different action workflow today, just the `arm64` and `amd64` _without_ `tmpfs`.

It [successfully builds these two containers](https://github.com/andrewn/librespot-docker/pkgs/container/librespot-docker), but they're still not linked.

My plan is to:

1. Get these two platform images to be linked under the `0.4.2` tag [using this `docker-manifest-action`](https://github.com/Noelware/docker-manifest-action) 
2. Get the `arm/v7` platform built and linked, probably using the `tmpfs` approach
3. Get `arm/v6` built and linked

> Have you tried it again today? Worth doing a re-run just to check whether it was actually network issues like some of the errors suggest, perhaps the GitHub workflows were just having a bit of a moment.

I can but I think avoiding the tmpfs step is a good idea.

**Comment by andrewn** [comment]
> 1. Get these two platform images to be linked under the `0.4.2` tag [using this `docker-manifest-action`](https://github.com/Noelware/docker-manifest-action)

 `arm64` and `amd64` are [building](https://github.com/andrewn/librespot-docker/actions/runs/4274652795), and [linked together on the containers page](https://github.com/andrewn/librespot-docker/pkgs/container/librespot-docker/73310190?tag=v0.4.2).

I switched to use the cargo's "sparse registry" which seems to keep memory under control. But I guess it'll take a few more runs to see if the builds are stable.

I'll move onto getting `arm/v7` and `arm/v6` building next 🤞

**Comment by andrewn** [comment]
I don't think rustup supports installing on arm6 for compilation. I found some docs about that [target being Tier 2 _without_ host tools](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-with-host-tools) which means it doesn't include cargo:

```
#12 2.643 rustup: installer for platform 'armv7-unknown-linux-musleabihf' not found, this may be unsupported
```

The sparse registry feature will be in Rust 1.68 which will be released next week, [March 09 2023](https://forge.rust-lang.org/index.html#current-release-versions). So I'm going to pause this until it's released and makes it's way into Alpine edge.

I'll try and build the `amd64` image locally and push to Docker which will at least unblock balena-labs-projects/balena-sound#623

**Comment by maggie0002** [comment]
Hey @andrewn,

I'm afraid I am no longer working at Balena. It looks like you're making good progress, but I would suggest posting on the forums of balenaSound repo where someone may pick it up.

**Comment by andrewn** [comment]
@maggie0002 Thanks for letting me know. 

All the best with whatever you're doing next and thanks for your help with this!

**Comment by andrewn** [comment]
Taking a step back, the reason we need to do this compilation at all is because the Alpine package of `librespot` compiles the ALSA backend and not the PulseAudio one. So I've [opened a PR](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/44657) for Alpine to include both, which will remove the need to compile at all.

**Pull request merged**
